version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/packages/askui-nodejs"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
