name: Build and Release Documentation
on:
  repository_dispatch:
    types: [askui_nodejs_package_released]
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docu-deployment.yml'
permissions: 
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Documentation
        run: npm run build -w docs
      - name: Deploy to Github Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs/dist
